name: Daily Random xkcd

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9:00 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.9'  # Specify the version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python script.py
