name: Update xkcd RSS Feed

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 8:00 AM Greek time (UTC+3)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_rss:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download seen_comics.json artifact (if it exists)
      - name: Download seen comics
        uses: actions/download-artifact@v3
        with:
          name: seen_comics
          path: seen_comics.json
        continue-on-error: true  # Proceed even if no artifact is found (e.g., first run)

      # Create seen_comics.json if it doesn't exist
      - name: Create seen_comics.json if missing
        run: |
          if [ ! -f seen_comics.json ]; then
            echo "[]" > seen_comics.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python generate_rss.py

      # Upload the updated seen_comics.json to persist it between runs
      - name: Upload updated seen comics
        uses: actions/upload-artifact@v3
        with:
          name: seen_comics
          path: seen_comics.json

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add xkcd_feed.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
