name: Generate xkcd RSS Feed

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 09:00 UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  generate_feed:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Generate RSS feed
        run: |
          python generate_rss.py
      
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add xkcd_feed.xml seen_comics.json
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
