name: Update xkcd HTML Page

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 8:00 AM Greek time (UTC+3)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_html:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to the repository contents

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest stable version

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest stable version
        with:
          python-version: '3.10'

      # Step 3: Install Python dependencies (including requests)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run the Python script to generate the HTML file
      - name: Run script
        run: python generate_html_404.py

      # Step 5: Commit and push the updated HTML file in 'docs' directory for GitHub Pages
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          
          # Check for changes and stash them if there are any
          if ! git diff-index --quiet HEAD --; then
            git stash -u  # Stash uncommitted changes
          fi

          git pull --rebase origin main  # Pull the latest changes from the remote main branch
          git add docs/xkcd_404_style.html
          git commit -m "Update XKCD 404-style HTML page" || echo "No changes to commit"
          git push origin main  # Explicitly push to the main branch

          # Apply stashed changes if any
          if git stash list | grep -q "stash@{0}"; then
            git stash pop  # Apply stashed changes
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub authentication token for pushing changes
